<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run()
    {
        DB::table('Product')->insert([
            [
                'Product_Name' => 'Luna Moon Pendant',
                'Description' => 'Delicate moon pendant on a fine gold-plated chain, perfect for everyday layering.',
                'Price' => 45.00,
                'Stock' => 2,
                'Image_URL' => 'assets/images/products/necklaces/luna-moon.png',
                'Metal' => 'Gold',
                'CategoryID' => 1,
            ],
            [
                'Product_Name' => 'Soulstone Bar Necklace',
                'Description' => 'A minimalist bar necklace set with a single ethically-sourced crystal.',
                'Price' => 52.00,
                'Stock' => 12,
                'Image_URL' => 'assets/images/products/necklaces/soulstone-bar.png',
                'Metal' => 'Gold',
                'CategoryID' => 1,
            ],
            [
                'Product_Name' => 'Aura Coin Necklace',
                'Description' => 'Hand-hammered coin pendant symbolising protection and clarity.',
                'Price' => 60.00,
                'Stock' => 12,
                'Image_URL' => 'assets/images/products/necklaces/aura-coin.jpg',
                'Metal' => 'Rose Gold',
                'CategoryID' => 1,
            ],

            [
                'Product_Name' => 'Harmony Bead Bracelet',
                'Description' => 'Hand-strung gemstones chosen to promote balance and calm.',
                'Price' => 35.00,
                'Stock' => 12,
                'Image_URL' => 'assets/images/products/bracelets/harmony-bead.png',
                'Metal' => 'Gold',
                'CategoryID' => 3,
            ],
            [
                'Product_Name' => 'Serenity Chain Bracelet',
                'Description' => 'Fine chain bracelet with subtle textured links for a soft shimmer.',
                'Price' => 40.00,
                'Stock' => 17,
                'Image_URL' => 'assets/images/products/bracelets/serenity-chain.png',
                'Metal' => 'Gold',
                'CategoryID' => 3,
            ],
            [
                'Product_Name' => 'Soul Cuff',
                'Description' => 'Adjustable cuff bracelet with a softly brushed finish.',
                'Price' => 40.00,
                'Stock' => 17,
                'Image_URL' => 'assets/images/products/bracelets/soul-cuff.png',
                'Metal' => 'Gold',
                'CategoryID' => 3,
            ],

            [
                'Product_Name' => 'Eclipse Stacking Ring',
                'Description' => 'Slim band finished with a subtle hammered texture, perfect for stacking.',
                'Price' => 29.99,
                'Stock' => 4,
                'Metal' => 'Gold',
                'Image_URL' => 'assets/images/products/rings/eclipse-stack.jpg',
                'CategoryID' => 4,
            ],
            [
                'Product_Name' => 'Solace Gemstone Ring',
                'Description' => 'Single gemstone ring in a classic claw setting.',
                'Price' => 55.75,
                'Stock' => 12,
                'Metal' => 'Gold',
                'Image_URL' => 'assets/images/products/rings/solace-gemstone.png',
                'CategoryID' => 4,
            ],
            [
                'Product_Name' => 'Orbit Signet Ring',
                'Description' => 'A modern signet ring with softly rounded edges.',
                'Price' => 55.75,
                'Stock' => 11,
                'Metal' => 'Gold',
                'Image_URL' => 'assets/images/products/rings/orbit-signet.jpg',
                'CategoryID' => 4,
            ],

            [
                'Product_Name' => 'Sterling Silver Bracelet',
                'Description' => 'Handcrafted sterling silver bracelet with intricate design.',
                'Price' => 35.50,
                'Stock' => 0,
                'Metal' => 'Silver',
                'Image_URL' => 'assets/images/products/bracelet1.jpg',
                'CategoryID' => 3,
            ],
            [
                'Product_Name' => 'Pearl Drop Earrings',
                'Description' => 'Elegant pearl drop earrings for special occasions.',
                'Price' => 55.00,
                'Stock' => 12,
                'Metal' => 'Silver',
                'Image_URL' => 'assets/images/products/earrings/earrings2.jpg',
                'CategoryID' => 2,
            ],
            [
                'Product_Name' => 'Twisted Rose Gold Hoops',
                'Description' => 'Elegant twisted hoop earrings with a polished finish.',
                'Price' => 34.99,
                'Stock' => 15,
                'Metal' => 'Rose Gold',
                'Image_URL' => 'assets/images/products/earrings/rose-gold-earrings-hoops.jpg',
                'CategoryID' => 2,
            ],
            [
                'Product_Name' => 'Pink Blossom Hoop Earrings',
                'Description' => 'Delicate hoop earrings featuring pink floral gemstone charms.',
                'Price' => 42.00,
                'Stock' => 10,
                'Metal' => 'Rose Gold',
                'Image_URL' => 'assets/images/products/earrings/flower rose-gold-earrings.jpg',
                'CategoryID' => 2,
            ],
            [
                'Product_Name' => 'Green Stone Drop Earrings',
                'Description' => 'Silver drop earrings with a deep green stone for a natural elegant look.',
                'Price' => 28.50,
                'Stock' => 12,
                'Metal' => 'Silver',
                'Image_URL' => 'assets/images/products/earrings/earth-stone-silver-earrings.jpg',
                'CategoryID' => 2,
            ],
            [
                'Product_Name' => 'Silver Block Pearl Earrings',
                'Description' => 'Minimal silver hoop earrings with block-style pearl drops.',
                'Price' => 30.00,
                'Stock' => 10,
                'Metal' => 'Silver',
                'Image_URL' => 'assets/images/products/earrings/silver-block-earrings.jpg',
                'CategoryID' => 2,
            ],
            [
                'Product_Name' => 'Floral Threader Earrings',
                'Description' => 'Elegant flower threader earrings with mixed silver and gold tones.',
                'Price' => 36.00,
                'Stock' => 8,
                'Metal' => 'Mixed Metal',
                'Image_URL' => 'assets/images/products/earrings/silver-gold-flower-earrings.jpg',
                'CategoryID' => 2,
            ],
            [
                'Product_Name' => 'Marble Stone Statement Earrings',
                'Description' => 'Bold gold statement earrings with a soft marbled stone finish.',
                'Price' => 45.00,
                'Stock' => 6,
                'Metal' => 'Gold',
                'Image_URL' => 'assets/images/products/earrings/gold-marble-earrings.png',
                'CategoryID' => 2,
            ],
            [
                'Product_Name' => 'Gold Leaf Statement Earrings',
                'Description' => 'Large textured gold leaf earrings designed for a bold look.',
                'Price' => 50.00,
                'Stock' => 5,
                'Metal' => 'Gold',
                'Image_URL' => 'assets/images/products/earrings/gold-leaf-earrings.jpg',
                'CategoryID' => 2,
            ],
            [
                'Product_Name' => 'Gold Teardrop Stud Earrings',
                'Description' => 'Minimal polished gold teardrop studs for everyday wear.',
                'Price' => 25.00,
                'Stock' => 14,
                'Metal' => 'Gold',
                'Image_URL' => 'assets/images/products/earrings/gold-teardrop-earrings.jpg',
                'CategoryID' => 2,
            ],
            [
                'Product_Name' => 'Chunky Gold Hoop Earrings',
                'Description' => 'Classic chunky gold hoop earrings with a smooth polished finish.',
                'Price' => 32.00,
                'Stock' => 20,
                'Metal' => 'Gold',
                'Image_URL' => 'assets/images/products/earrings/chunky gold hoops earrings.jpg',
                'CategoryID' => 2,
            ],
            [
                'Product_Name' => 'Dainty Diamond Rose Gold Necklace',
                'Description' => 'Minimal rose gold necklace with a delicate row of small diamonds.',
                'Price' => 48.00,
                'Stock' => 10,
                'Metal' => 'Rose Gold',
                'Image_URL' => 'assets/images/products/necklaces/small-diamond-rose-gold-necklace.jpg',
                'CategoryID' => 1,
            ],
            [
                'Product_Name' => 'Diamond Rose Gold Necklace',
                'Description' => 'Elegant rose gold necklace with a fine diamond bar detail.',
                'Price' => 65.00,
                'Stock' => 8,
                'Metal' => 'Rose Gold',
                'Image_URL' => 'assets/images/products/necklaces/diamond rose gold necklace.jpg',
                'CategoryID' => 1,
            ],
            [
                'Product_Name' => 'Rose Gold Circle Necklace',
                'Description' => 'Layered rose gold necklace set with a modern circular pendant.',
                'Price' => 54.00,
                'Stock' => 9,
                'Metal' => 'Rose Gold',
                'Image_URL' => 'assets/images/products/necklaces/rose-gold-circle-necklace.jpg',
                'CategoryID' => 1,
            ],
            [
                'Product_Name' => 'Pearl Silver Necklace',
                'Description' => 'Layered silver necklace styled with pearl strands and a pendant detail.',
                'Price' => 58.00,
                'Stock' => 7,
                'Metal' => 'Silver',
                'Image_URL' => 'assets/images/products/necklaces/pearl-silver-necklace.jpg',
                'CategoryID' => 1,
            ],
            [
                'Product_Name' => 'Dainty Heart Silver Necklace',
                'Description' => 'Simple silver necklace with a small heart charm for everyday wear.',
                'Price' => 35.00,
                'Stock' => 15,
                'Metal' => 'Silver',
                'Image_URL' => 'assets/images/products/necklaces/silver-danity-heart-necklace.jpg',
                'CategoryID' => 1,
            ],
            [
                'Product_Name' => 'Gold Stack Initial Necklace',
                'Description' => 'Layered gold necklace set featuring an initial pendant.',
                'Price' => 52.00,
                'Stock' => 7,
                'Metal' => 'Gold',
                'Image_URL' => 'assets/images/products/necklaces/gold stack with letter necklace.jpg',
                'CategoryID' => 1,
            ],
            [
                'Product_Name' => 'Pearl Gold Necklace',
                'Description' => 'Gold necklace layered with pearls and a soft pearl drop pendant.',
                'Price' => 49.00,
                'Stock' => 11,
                'Metal' => 'Gold',
                'Image_URL' => 'assets/images/products/necklaces/pearl-gold-necklace.jpg',
                'CategoryID' => 1,
            ],
            [
                'Product_Name' => 'Rose Gold Diamond Open Ring',
                'Description' => 'Elegant open ring with delicate diamond detailing in rose gold.',
                'Price' => 39.99,
                'Stock' => 10,
                'Metal' => 'Rose Gold',
                'Image_URL' => 'assets/images/products/rings/rose-gold-small-diamonds-ring.jpg',
                'CategoryID' => 4,
            ],
            [
                'Product_Name' => 'Rose Gold Leaf Diamond Ring',
                'Description' => 'Nature-inspired rose gold ring with leaf-shaped diamond accents.',
                'Price' => 49.99,
                'Stock' => 8,
                'Metal' => 'Rose Gold',
                'Image_URL' => 'assets/images/products/rings/rose-gold-diamond-ring.jpg',
                'CategoryID' => 4,
            ],
            [
                'Product_Name' => 'Blue Silver Flower Ring',
                'Description' => 'Silver ring featuring a delicate blue floral gemstone design.',
                'Price' => 27.99,
                'Stock' => 12,
                'Metal' => 'Silver',
                'Image_URL' => 'assets/images/products/rings/blue-silver-ring.jpg',
                'CategoryID' => 4,
            ],
            [
                'Product_Name' => 'Silver Leaf Wrap Ring',
                'Description' => 'Minimal silver wrap ring with leaf detailing for a natural aesthetic.',
                'Price' => 24.99,
                'Stock' => 14,
                'Metal' => 'Silver',
                'Image_URL' => 'assets/images/products/rings/silver-leaf-ring.jpg',
                'CategoryID' => 4,
            ],
            [
                'Product_Name' => 'Gold Lotus Ring',
                'Description' => 'Elegant gold lotus ring with a central stone for a symbolic finish.',
                'Price' => 29.99,
                'Stock' => 10,
                'Metal' => 'Gold',
                'Image_URL' => 'assets/images/products/rings/gold-lotus-ring.jpg',
                'CategoryID' => 4,
            ],
            [
                'Product_Name' => 'Floral Gold Statement Ring',
                'Description' => 'Detailed gold ring with a floral design for a bold yet elegant look.',
                'Price' => 34.99,
                'Stock' => 9,
                'Metal' => 'Gold',
                'Image_URL' => 'assets/images/products/rings/floral-gold-ring.jpg',
                'CategoryID' => 4,
            ],
            [
                'Product_Name' => 'Gold Stack Ring Set',
                'Description' => 'Minimal stacked gold rings for a layered modern style.',
                'Price' => 31.99,
                'Stock' => 11,
                'Metal' => 'Gold',
                'Image_URL' => 'assets/images/products/rings/gold-stack-ring.jpg',
                'CategoryID' => 4,
            ],
            [
                'Product_Name' => 'Dainty Silver Bracelet',
                'Description' => 'Minimal silver bracelet with a fine chain design.',
                'Price' => 22.99,
                'Stock' => 15,
                'Metal' => 'Silver',
                'Image_URL' => 'assets/images/products/bracelets/danity-silver-bracelet.jpg',
                'CategoryID' => 3,
            ],
            [
                'Product_Name' => 'Pearl Silver Stack Bracelet',
                'Description' => 'Layered bracelet set combining pearls and silver chains.',
                'Price' => 39.99,
                'Stock' => 10,
                'Metal' => 'Silver',
                'Image_URL' => 'assets/images/products/bracelets/silver-pearl-stack-bracelet.jpg',
                'CategoryID' => 3,
            ],
            [
                'Product_Name' => 'Gold Floral Stack Bracelet',
                'Description' => 'Elegant gold bracelet set with floral and gemstone accents.',
                'Price' => 44.99,
                'Stock' => 8,
                'Metal' => 'Gold',
                'Image_URL' => 'assets/images/products/bracelets/gold-floral-stack-bracelet.jpg',
                'CategoryID' => 3,
            ],
            [
                'Product_Name' => 'Gold Pearl Stack Bracelet',
                'Description' => 'Layered gold bracelet featuring pearl and chain combinations.',
                'Price' => 42.99,
                'Stock' => 9,
                'Metal' => 'Gold',
                'Image_URL' => 'assets/images/products/bracelets/gold-pearl-stack-bracelet.jpg',
                'CategoryID' => 3,
            ],
            [
                'Product_Name' => 'Rose Gold Pearl Bracelet',
                'Description' => 'Delicate rose gold bracelet with a single pearl feature.',
                'Price' => 36.99,
                'Stock' => 11,
                'Metal' => 'Rose Gold',
                'Image_URL' => 'assets/images/products/bracelets/pearl-stack-rose-gold-bracelet.jpg',
                'CategoryID' => 3,
            ],
            [
                'Product_Name' => 'Rose Gold Dainty Stack Bracelet',
                'Description' => 'Minimal layered rose gold bracelet set with subtle gemstone details.',
                'Price' => 38.99,
                'Stock' => 10,
                'Metal' => 'Rose Gold',
                'Image_URL' => 'assets/images/products/bracelets/danity-stack-rose-gold-bracelet.jpg',
                'CategoryID' => 3,
            ],
        ]);
    }
}
